### ISSUE TITLE
Schedule: Create list-style component to enumerate the Colorado Mormon Chorale Schedule

### ISSUE THREAD

**Issue by abelgoodwin1988** [abelgoodwin1988/coloradomormonchorale#15]
Use the mock data that @Maxbrain0 will be creating from a mock-data-api to create a list of items for the schedule page.

**Comment by Maxbrain0** [comment]
@abelgoodwin1988,

Since I have created some mock data in #16 , I want to work on this component to test enumerating the data on the performances page.

Maybe we should pull this into that issue as well. Don't know if that's doable.
